import api
from static import Intent

api.send_transaction(Intent.ADD_PRODUCT, code='123345')
print()
api.send_transaction(Intent.ADD_BAGS, code='1111111')
print()
api.send_transaction(Intent.REMOVE_PRODUCT, code='123345')
print()
api.send_transaction(Intent.REMOVE_BAGS, code='1111111')
print()
api.send_transaction(Intent.REMOVE_PRODUCT, position='10')
print()
api.send_transaction(Intent.REQUEST_WEIGHTING, code='123345')
print()
api.send_transaction(Intent.REQUEST_PAYMENT)
print()
api.send_transaction(Intent.PASS_LOYALTY, code='54321')
print()
api.send_transaction(Intent.ADD_PROMO_CODE, code='777')
print()
api.send_transaction(Intent.SPEND_BONUS, amount='3345')
print()
api.send_transaction(Intent.CANCEL_ORDER)
print()
api.send_transaction(Intent.CANCEL_PAYMENT)
print()
api.send_transaction(Intent.REQUEST_PAYMENT, final=True)
